version: '3'

services:

  8.0-ubuntu18:
    build:
      context: ./ubuntu-18
      dockerfile: ../Dockerfile
      args:
        BUILDER_VERSION: ubuntu18
        LLVM_VERSION: '8'
    image: odaceo/clang:8.0-ubuntu18
